### ISSUE TITLE
Malfunction when cleanTorrent is running

### ISSUE THREAD

**Issue by alickmchang** [acwong00/Clean-Torrents#1]
Hello, I saw your post on SegmentFault, and have "parse-torrent" package and "MD5" package installed. However, the scripts did not run well.

Error messages are as follows:

/Users/changmin/GitHub/Clean-Torrents/cleanTorrent.js:30
    for (var i = 0; i < files.length; i++) {
                             ^
TypeError: Cannot read property 'length' of undefined
    at cleanInfo (/Users/changmin/GitHub/Clean-Torrents/cleanTorrent.js:30:30)
    at main (/Users/changmin/GitHub/Clean-Torrents/cleanTorrent.js:11:25)
    at Object.<anonymous> (/Users/changmin/GitHub/Clean-Torrents/cleanTorrent.js:45:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

Is there anything wrong with my operation? Many thanks for your help.

**Comment by acwong00** [comment]
@alick19 Thanks for your question. Some torrent file which just contains little content  don't have a file object. I suggest you print the **info** object of your torrent file to see whether the file contains the file object.

``` javascript
var info = parseTorrent(fs.readFileSync('my.torrent'));
console.log(info);
```

My English is not good. I hope it helps.

**Comment by alickmchang** [comment]
Thanks for your reply. I think my torrent has a file object. 

{ info: 
   { length: 1063461033,
     name: <Buffer 58 2d 41 72 74 20 2d 20 41 6c 6d 6f 73 74 20 46 61 6d 6f 75 73 20 2d 20 41 6e 67 65 6c 69 63 61 20 5b 31 30 38 30 70 5d 2e 6d 6f 76>,
     'piece length': 262144,
     pieces: <Buffer a2 0f 70 8e 2c 36 1f 6e 1b 5b 11 54 25 e2 eb 5f 3e 9e 37 38 9d 11 e8 99 e7 d2 e0 76 48 53 6c 23 a5 80 ff 0e a6 b4 26 db a5 fb 6c d5 39 e9 c4 ba 3b 95 0f ...> },
  infoBuffer: <Buffer 64 36 3a 6c 65 6e 67 74 68 69 31 30 36 33 34 36 31 30 33 33 65 34 3a 6e 61 6d 65 34 34 3a 58 2d 41 72 74 20 2d 20 41 6c 6d 6f 73 74 20 46 61 6d 6f 75 73 ...>,
  infoHash: 'f263df1d141921549330cdb51ddc487d1dd51a43',
  name: 'X-Art - Almost Famous - Angelica [1080p].mov',
  private: false,
  created: Fri Sep 27 2013 22:11:31 GMT+0800 (CST),
  comment: 'Torrent downloaded from torrent cache at http://torcache.net/',
  announceList: 
   [ [ 'udp://tracker.publicbt.com:80/announce' ],
     [ 'udp://tracker.openbittorrent.com:80/announce' ],
     [ 'udp://tracker.istole.it:80/announce' ],
     [ 'http://tracker.trackerfix.com/announce' ],
     [ 'http://fr33dom.h33t.com:3310/announce' ],
     [ 'udp://9.rarbg.me:2710/announce' ],
     [ 'udp://9.rarbg.com:2710/announce' ],
     [ 'udp://ipv4.tracker.harry.lu:80/announce' ],
     [ 'udp://open.demonii.com:1337/announce' ],
     [ 'udp://fr33domtracker.h33t.com:3310/announce' ] ],
  announce: 
   [ 'udp://tracker.publicbt.com:80/announce',
     'udp://tracker.openbittorrent.com:80/announce',
     'udp://tracker.istole.it:80/announce',
     'http://tracker.trackerfix.com/announce',
     'http://fr33dom.h33t.com:3310/announce',
     'udp://9.rarbg.me:2710/announce',
     'udp://9.rarbg.com:2710/announce',
     'udp://ipv4.tracker.harry.lu:80/announce',
     'udp://open.demonii.com:1337/announce',
     'udp://fr33domtracker.h33t.com:3310/announce' ],
  urlList: [],
  files: 
   [ { path: 'X-Art - Almost Famous - Angelica [1080p].mov',
       name: 'X-Art - Almost Famous - Angelica [1080p].mov',
       length: 1063461033,
       offset: 0 } ],
  length: 1063461033,
  pieceLength: 262144,
  lastPieceLength: 204969,
  pieces: 
   [ 'a20f708e2c361f6e1b5b115425e2eb5f3e9e3738',
     '9d11e899e7d2e07648536c23a580ff0ea6b426db',
     'a5fb6cd539e9c4ba3b950fc2a796713da07db680',
     'ef2d411a0d297c895924e3a3bd47f22781abc2a8',
     '2684998322ec7a3d9eff9f511c79a738d89aad78',

**Comment by acwong00** [comment]
@alick19  I see, your torrent file is a little bit different from common files. My code is base on the torrent structure of [Wikipedia's](http://zh.wikipedia.org/wiki/%E7%A7%8D%E5%AD%90%E6%96%87%E4%BB%B6) introduction. The files object is included in info object. But, according to your console information your info object and files object are in the same level so that you can't get the same results.

**Comment by alickmchang** [comment]
@acwong00 Oh what a pity...

**Comment by acwong00** [comment]
@alick19 Hello, I just updated my Clean-Torrents script. You can try again to see if your problem solved.

**Comment by alickmchang** [comment]
@acwong00 Still not working...

module.js:340
    throw err;
          ^
Error: Cannot find module 'nt'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/changmin/GitHub/Clean-Torrents/cleanTorrent.js:3:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

**Comment by acwong00** [comment]
@alick19  You need to install relate libraries.

**Comment by alickmchang** [comment]
@acwong00 Oops, I'm new to Nodejs... Thanks, finally the new torrent was successfully generated, but the file still couldn't be downloaded via Baidu Cloud or Thunder...

**Comment by acwong00** [comment]
@alick19 This technology is not working now in Baidu Cloud or Thunder. You can just treate it to a study.....
